spring:
  datasource:
    url: "jdbc:mysql://localhost/springboot_security_demo?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=false"
    username: "root"
    password: "123456"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.security: info

