spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/security_demo
    username: postgres
    password: 123456
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.security: info

