spring:
  profiles:
    active: dev
  application:
    name: demo

server:
  port: 8080

logging:
  file: logs/${spring.application.name}.log


jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: /auth
      refresh: /refresh

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger-resources/api-docs