spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  profiles:
    active: dev
  application:
    name: demo
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

server:
  port: 9095

logging:
  file: logs/${spring.application.name}.log


jwt:
  header: Authorization
  secret: mySecret
  expiration: 604800
  route:
    authentication:
      path: /auth
      refresh: /refresh

springfox:
  documentation:
    swagger:
      v2:
        path: /swagger-resources/api-docs